# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Convocation',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='convocation',
        ),
        migrations.AlterField(
            model_name='vote',
            name='types',
            field=models.SmallIntegerField(choices=[(1, 'За основу'), (2, 'За пропозицію'), (3, 'В цілому'), (4, 'За правку')], verbose_name='тип'),
        ),
    ]
