# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170502_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='types',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'За основу'), (2, 'За пропозицію'), (3, 'В цілому'), (4, 'За правку')], null=True, verbose_name='тип'),
        ),
    ]
