# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170502_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='название'),
        ),
    ]
