# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170502_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True, verbose_name='ФИО')),
            ],
            options={
                'verbose_name_plural': 'депутаты',
                'verbose_name': 'депутата',
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.SmallIntegerField(choices=[(1, 'За'), (2, 'Проти'), (3, 'Утримався'), (4, 'Не голосував'), (5, 'Відсутній')], verbose_name='результат')),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Deputy', verbose_name='депутат')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vote', verbose_name='голосование')),
            ],
            options={
                'verbose_name_plural': 'голоса',
                'verbose_name': 'голос',
            },
        ),
        migrations.AlterUniqueTogether(
            name='voice',
            unique_together=set([('deputy', 'vote')]),
        ),
    ]
