# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170502_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='absent',
            field=models.SmallIntegerField(default=0, verbose_name='отсуствуют'),
        ),
        migrations.AddField(
            model_name='vote',
            name='abstained',
            field=models.SmallIntegerField(default=0, verbose_name='воздержались'),
        ),
        migrations.AddField(
            model_name='vote',
            name='agree',
            field=models.SmallIntegerField(default=0, verbose_name='за'),
        ),
        migrations.AddField(
            model_name='vote',
            name='did_not_participate',
            field=models.SmallIntegerField(default=0, verbose_name='не принимали участие'),
        ),
        migrations.AddField(
            model_name='vote',
            name='disagree',
            field=models.SmallIntegerField(default=0, verbose_name='против'),
        ),
        migrations.AddField(
            model_name='vote',
            name='result',
            field=models.SmallIntegerField(choices=[(1, 'Принято'), (2, 'Не принято')], default=1, verbose_name='решение'),
            preserve_default=False,
        ),
    ]
